const cards = [
  ['Chronicles of Narnia', 'category-2', 'category-3', 'category-4', 'category-5', 'category-6'],
  ['page-1', 'page-2', 'page-3', 'page-4', 'page-5', 'page-6'],
  [
    [
      {
        word: 'pray',
        translation: 'молиться',
        audioSrc: 'audio2/pray-us.mp3',
        audioQuote: 'MR/ringtones/pray.mp3',
        textQuote: 'Then I parted my clothes where I thought the readiest way lay to my heart and I prayed to all the gods that as soon as I was dead I might find myself with my brother.',
        chapter: 'CHAPTER THREE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/#/toc3',
      },
      {
        word: 'belong',
        translation: 'принадлежать',
        audioSrc: 'audio2/belong-us.mp3',
        audioQuote: 'MR/ringtones/belong.mp3',
        textQuote: 'He turned and looked behind him and saw that the slope on which he was standing belonged to a range of far higher mountains.',
        chapter: 'CHAPTER TWELVE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'against',
        translation: 'против',
        audioSrc: 'audio2/against-us.mp3',
        audioQuote: 'MR/music/against.mp3',
        textQuote: 'But Bree had two reasons against this.',
        chapter: 'CHAPTER THREE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/#/toc3',
      },
      {
        word: 'explain',
        translation: 'объяснять',
        audioSrc: 'audio2/explain-us.mp3',
        audioQuote: 'MR/music/explain.mp3',
        textQuote: 'But Bree explained that there were gardens and pleasure houses on both banks of the river',
        chapter: 'CHAPTER THREE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/#/toc3',
      },
      {
        word: 'bow',
        translation: 'кланяться',
        audioSrc: 'audio2/bow-us.mp3',
        audioQuote: 'MR/ringtones/bow.mp3',
        textQuote: '...he bowed kneeling before him till his beard touched the earth and made signs to Shasta to kneel also.',
        chapter: 'CHAPTER ONE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'approve',
        translation: 'одобрять',
        audioSrc: 'audio2/approve-us.mp3',
        audioQuote: 'MR/music/approve.mp3',
        textQuote: 'But she approved of the idea of disguise as well.',
        chapter: 'CHAPTER THREE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/#/toc3',
      },
      {
        word: 'avoid',
        translation: 'избегать',
        audioSrc: 'audio2/avoid-us.mp3',
        audioQuote: 'MR/music/avoid.mp3',
        textQuote: 'For the next few minutes Shasta was at work, very cautiously to avoid jingling',
        chapter: 'CHAPTER ONE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'recall',
        translation: 'вспоминать',
        audioSrc: 'audio2/recall-us.mp3',
        audioQuote: 'MR/music/recall.mp3',
        textQuote: 'Peter leant back with half-closed eyes and recalled to his mind the language in which he had written such things long ago in Narnia\'s golden age.',
        chapter: 'CHAPTER THIRTEEN',
        book: 'Prince Caspian',
        link: 'https://predanie.ru/book/218227-prince-caspian/',
      },
    ],

    [
      {
        word: 'hire',
        translation: 'нанимать',
        audioSrc: 'audio2/hire-us.mp3',
        audioQuote: 'MR/ringtones/hire.mp3',
        textQuote: 'For if I sell the boy I must undoubtedly either buy or hire another to do his work',
        chapter: 'CHAPTER ONE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'fumble',
        translation: 'нащупывать',
        audioSrc: 'audio2/fumble-us.mp3',
        audioQuote: 'MR/music/fumble.mp3',
        textQuote: '',
        chapter: '',
        book: '',
        link: '',
      },
      {
        word: 'deprive',
        translation: 'лишать',
        audioSrc: 'audio2/deprive-us.mp3',
        audioQuote: 'MR/ringtones/deprive.mp3',
        textQuote: 'See what your Highness has done,” said King Edmund. “Deprived us of a proved warrior on the very edge of battle.',
        chapter: 'CHAPTER TWELVE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'contempt',
        translation: 'презрение',
        audioSrc: 'audio2/contempt-us.mp3',
        audioQuote: 'MR/music/contempt.mp3',
        textQuote: '“Ridden the what?” retorted the Horse with extreme contempt.',
        chapter: 'CHAPTER ONE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'achieve',
        translation: 'достигать',
        image: 'img/run.jpg',
        audioSrc: 'audio2/achieve-us.mp3',
        audioQuote: 'MR/music/achieve.mp3',
        textQuote: '',
        chapter: '',
        book: '',
        link: '',
      },
      {
        word: 'extend',
        translation: 'вытягивать, расширять',
        audioSrc: 'audio2/extend-us.mp3',
        audioQuote: 'MR/ringtones/extend.mp3',
        textQuote: 'Shasta could see all the terrible claws extended.',
        chapter: 'CHAPTER TEN',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'recognize',
        translation: 'узнавать',
        image: 'img/skip.jpg',
        audioSrc: 'audio2/recognize-us.mp3',
        audioQuote: 'MR/music/recognize.mp3',
        textQuote: 'In fact it would be the most likely place in the world for meeting someone who would recognize Aravis or even himself.',
        chapter: 'CHAPTER THREE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'offer',
        translation: 'предложение',
        audioSrc: 'audio2/offer-us.mp3',
        audioQuote: 'MR/ringtones/offer.mp3',
        textQuote: '...and the offer was favourably accepted...',
        chapter: 'CHAPTER THREE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
    ],

    [
      {
        word: 'rub',
        translation: 'тереть',
        audioSrc: 'audio2/rub-us.mp3',
        audioQuote: 'MR/music/rub.mp3',
        textQuote: 'That’s good. That’s very good,” he said, rubbing his back on the turf and waving all four legs in the air. ',
        chapter: 'CHAPTER TWO',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'stuff',
        translation: 'вещи, хлам',
        audioSrc: 'audio2/stuff-us.mp3',
        audioQuote: 'MR/ringtones/stuff.mp3',
        textQuote: 'All we need is some pretext for going down to our ship today and taking stuff on board',
        chapter: 'CHAPTER FIVE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'suppose',
        translation: 'полагать',
        audioSrc: 'audio2/suppose-us.mp3',
        audioQuote: 'MR/music/suppose.mp3',
        textQuote: '“I suppose anyone can fall,” said Shasta.',
        chapter: 'CHAPTER ONE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'wish',
        translation: 'страстно желать',
        audioSrc: 'audio2/wish-us.mp3',
        audioQuote: 'MR/music/wish.mp3',
        textQuote: '“don’t I just wish I was big enough to punch your head!”',
        chapter: 'CHAPTER TWO',
        book: 'The Magician’s Nephew',
        link: 'https://predanie.ru/book/218224-the-magician-s-nephew/',
      },
      {
        word: 'hesitate',
        translation: 'колебаться',
        audioSrc: 'audio2/hesitate-us.mp3',
        audioQuote: 'MR/ringtones/hesitate.mp3',
        textQuote: 'He spoke in such a voice that neither Caspian nor the others hesitated for a moment: it now seemed to them quite possible that they might win a war...',
        chapter: 'CHAPTER SIX',
        book: 'Prince Caspian',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'chase',
        translation: 'преследовать',
        audioSrc: 'audio2/chase-us.mp3',
        audioQuote: 'MR/ringtones/chase.mp3',
        textQuote: 'And that is the pith of my story until this very night when I was chased by lions and met you at the swimming of the salt water.',
        chapter: 'CHAPTER THREE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'hide',
        translation: 'прятать',
        audioSrc: 'audio2/hide-us.mp3',
        audioQuote: 'MR/ringtones/hide.mp3',
        textQuote: 'All these years I have been a slave to humans, hiding my true nature and pretending to be dumb and witless like their horses.',
        chapter: 'CHAPTER ONE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'path',
        translation: 'тропа',
        audioSrc: 'audio2/path-us.mp3',
        audioQuote: 'MR/ringtones/path.mp3',
        textQuote: 'Then the path went left and south away from the cliff ',
        chapter: 'CHAPTER THIRTEEN',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
    ],

    [
      {
        word: 'weep',
        translation: 'плакать',
        audioSrc: 'audio2/weep-us.mp3',
        audioQuote: 'MR/ringtones/weep.mp3',
        textQuote: 'Then I parted my clothes where I thought the readiest way lay to my heart and I prayed to all the gods that as soon as I was dead I might find myself with my brother.',
        chapter: 'CHAPTER THREE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'stagger',
        translation: 'шататься',
        audioSrc: 'audio2/stagger-us.mp3',
        audioQuote: 'MR/ringtones/stagger.mp3',
        textQuote: 'Then I parted my clothes where I thought the readiest way lay to my heart and I prayed to all the gods that as soon as I was dead I might find myself with my brother.',
        chapter: '',
        book: '',
        link: '',
      },
      {
        word: 'persuade',
        translation: 'уговорить',
        audioSrc: 'audio2/persuade-us.mp3',
        audioQuote: 'MR/ringtones/persuade.mp3',
        textQuote: 'And so she persuaded my father to promise me in marriage to Ahoshta Tarkaan.',
        chapter: 'CHAPTER THREE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'observe',
        translation: 'заметить',
        audioSrc: 'audio2/observe-us.mp3',
        audioQuote: 'MR/ringtones/observed.mp3',
        textQuote: '“I do not see these fifty warriors,” observed Reepicheep.',
        chapter: 'CHAPTER NINE',
        book: 'The Voyage of the ‘Dawn Treader’',
        link: 'https://predanie.ru/book/218228-the-voyage-of-the-dawn-treader/#/toc9',
      },
      {
        word: 'force',
        translation: 'воздействовать',
        audioSrc: 'audio2/force-us.mp3',
        audioQuote: 'MR/ringtones/force.mp3',
        textQuote: 'the Voice continued. “I was the lion who forced you to join with Aravis.',
        chapter: 'CHAPTER ELEVEN',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/#/toc11',
      },
      {
        word: 'shore',
        translation: 'берег',
        audioSrc: 'audio2/shore-us.mp3',
        audioQuote: 'MR/ringtones/shore.mp3',
        textQuote: 'And I was the lion you do not remember who pushed the boat in which you lay, a child near death, so that it came to shore where a man sat, wakeful at midnight, to receive you.',
        chapter: 'CHAPTER ELEVEN',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/#/toc11',
      },
      {
        word: 'vicious',
        translation: 'порочный, злой',
        audioSrc: 'audio2/vicious-us.mp3',
        audioQuote: 'MR/ringtones/vicious.mp3',
        textQuote: '',
        chapter: '',
        book: '',
        link: '',
      },
      {
        word: 'route',
        translation: 'маршрут',
        audioSrc: 'audio2/route-us.mp3',
        audioQuote: 'MR/ringtones/route.mp3',
        textQuote: '',
        chapter: '',
        book: '',
        link: '',
      },
    ],

    [
      {
        word: 'seldom',
        translation: 'редко',
        audioSrc: 'audio2/seldom.mp3',
        audioQuote: 'MR/ringtones/seldom.mp3',
        textQuote: 'That is why you so seldom find more than one dragon in the same county.',
        chapter: 'CHAPTER SIX',
        book: 'The Voyage of the ‘Dawn Treader’',
        link: 'https://predanie.ru/book/218228-the-voyage-of-the-dawn-treader/',
      },
      {
        word: 'boast',
        translation: 'хвалиться',
        audioSrc: 'audio2/boast.mp3',
        audioQuote: 'MR/ringtones/boast.mp3',
        textQuote: 'And that is what shames me most of all. I, who called myself a war-horse and boasted of a hundred fights, to be beaten by a little human boy—a child, a mere foal, who had never held a sword nor had any good nurture or example in his life!”',
        chapter: 'CHAPTER TEN',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'deceive',
        translation: 'обманывать',
        audioSrc: 'audio2/deceive.mp3',
        audioQuote: 'MR/ringtones/deceive.mp3',
        textQuote: 'Now for three days and more I knew that my father would not seek me, being deceived by the words I had said to him. ',
        chapter: 'CHAPTER THREE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'deny',
        translation: 'отрицать',
        audioSrc: 'audio2/deny.mp3',
        audioQuote: 'MR/ringtones/deny.mp3',
        textQuote: '“I must confess—I cannot deny it—that I am deeply disappointed in the result of the operation,” came the answer. ',
        chapter: 'CHAPTER TWELVE',
        book: 'Prince Caspian',
        link: 'https://predanie.ru/book/218227-prince-caspian/',
      },
      {
        word: 'distract',
        translation: 'отвлекать',
        audioSrc: 'audio2/distract.mp3',
        audioQuote: 'MR/ringtones/distract.mp3',
        textQuote: 'O my son, do not allow your mind to be distracted by idle questions',
        chapter: 'CHAPTER THREE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'acknowledge',
        translation: 'признавать',
        audioSrc: 'audio2/acknowledge.mp3',
        audioQuote: 'MR/ringtones/acknowledge.mp3',
        textQuote: ' Does he still acknowledge the King of Narnia for his lord?',
        chapter: 'CHAPTER THREE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'traitor',
        translation: 'предатель',
        audioSrc: 'audio2/traitor.mp3',
        audioQuote: 'MR/ringtones/traitor.mp3',
        textQuote: 'It was very unpleasant to think of all those nice people imagining him a traitor.',
        chapter: 'CHAPTER SIX',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'induce',
        translation: 'побуждать, заставлять',
        audioSrc: 'audio2/induce.mp3',
        audioQuote: 'MR/ringtones/induce.mp3',
        textQuote: 'what price could induce your servant, poor though he is, to sell into slavery his only child and his own flesh?',
        chapter: 'CHAPTER ONE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
    ],

    [
      {
        word: 'weary',
        translation: 'уставший',
        audioSrc: 'audio2/weary.mp3',
        audioQuote: 'MR/ringtones/weary.mp3',
        textQuote: "They're brave fellows, but I set signs that some of them are weary of the voyage and long to have our prow pointing to Narnia again.",
        chapter: 'CHAPTER FOURTEEN.',
        book: 'The Voyage of the ‘Dawn Treader’',
        link: 'https://predanie.ru/book/218228-the-voyage-of-the-dawn-treader/',
      },
      {
        word: 'yell',
        translation: 'кричать',
        audioSrc: 'audio2/yell.mp3',
        audioQuote: 'MR/ringtones/yell.mp3',
        textQuote: '“Come on, Bree, come on,” yelled Aravis over her shoulder.',
        chapter: 'CHAPTER TEN',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'dumb',
        translation: 'немой',
        audioSrc: 'audio2/dumb.mp3',
        audioQuote: 'MR/ringtones/dumb.mp3',
        textQuote: 'You see, he thinks I’m dumb and witless like his other horses.',
        chapter: 'CHAPTER ONE',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/',
      },
      {
        word: 'tangle',
        translation: 'запутывать, сплетение',
        audioSrc: 'audio2/tangle.mp3',
        audioQuote: 'MR/ringtones/tangle.mp3',
        textQuote: 'The wood was so thick and tangled that they could hardly see into it at all.',
        chapter: 'CHAPTER ONE',
        book: 'Prince Caspian',
        link: 'https://predanie.ru/book/218227-prince-caspian/#/toc1',
      },
      {
        word: 'grave',
        translation: 'серьезный',
        audioSrc: 'audio2/grave.mp3',
        audioQuote: 'MR/ringtones/grave.mp3',
        textQuote: 'And instead of being grave and mysterious like most Calormenes, they walked with a swing and let their arms and shoulders free, and chatted and laughed.',
        chapter: 'CHAPTER FOUR',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/#/toc4',
      },
      {
        word: 'endure',
        translation: 'терпеть, переносить',
        audioSrc: 'audio2/endure.mp3',
        audioQuote: 'MR/ringtones/endure.mp3',
        textQuote: 'Many terrors I endured, many spells did I utter, to find it, when I was still young.',
        chapter: 'CHAPTER FIVE',
        book: 'Prince Caspian',
        link: 'https://predanie.ru/book/218227-prince-caspian/#/toc5',
      },
      {
        word: 'sniff',
        translation: 'нюхать',
        audioSrc: 'audio2/sniff.mp3',
        audioQuote: 'MR/ringtones/sniff.mp3',
        textQuote: 'They stood sniffing in the sea-smell.',
        chapter: 'CHAPTER ONE',
        book: 'Prince Caspian',
        link: 'https://predanie.ru/book/218227-prince-caspian/#/toc1',
      },
      {
        word: 'steep',
        translation: 'крутой',
        audioSrc: 'audio2/steep.mp3',
        audioQuote: 'MR/ringtones/steep.mp3',
        textQuote: 'They soon turned to the left and began going up a steep hill.',
        chapter: 'CHAPTER FOUR',
        book: 'The Horse and His Boy',
        link: 'https://predanie.ru/book/218226-the-horse-and-his-boy/#/toc4',
      },
    ],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
  ],
  [
    [
      {
        word: 'cry',
        translation: 'плакать',
        image: 'img/cry.jpg',
        audioSrc: 'audio/cry.mp3',
      },
      {
        word: 'dance',
        translation: 'танцевать',
        image: 'img/dance.jpg',
        audioSrc: 'audio/dance.mp3',
      },
      {
        word: 'dive',
        translation: 'нырять',
        image: 'img/dive.jpg',
        audioSrc: 'audio/dive.mp3',
      },
      {
        word: 'draw',
        translation: 'рисовать',
        image: 'img/draw.jpg',
        audioSrc: 'audio/draw.mp3',
      },
      {
        word: 'fish',
        translation: 'ловить рыбу',
        image: 'img/fish.jpg',
        audioSrc: 'audio/fish.mp3',
      },
      {
        word: 'fly',
        translation: 'летать',
        image: 'img/fly.jpg',
        audioSrc: 'audio/fly.mp3',
      },
      {
        word: 'hug',
        translation: 'обнимать',
        image: 'img/hug.jpg',
        audioSrc: 'audio/hug.mp3',
      },
      {
        word: 'jump',
        translation: 'прыгать',
        image: 'img/jump.jpg',
        audioSrc: 'audio/jump.mp3',
      },
    ],

    [
      {
        word: 'open',
        translation: 'открывать',
        image: 'img/open.jpg',
        audioSrc: 'audio/open.mp3',
      },
      {
        word: 'play',
        translation: 'играть',
        image: 'img/play.jpg',
        audioSrc: 'audio/play.mp3',
      },
      {
        word: 'point',
        translation: 'указывать',
        image: 'img/point.jpg',
        audioSrc: 'audio/point.mp3',
      },
      {
        word: 'ride',
        translation: 'ездить',
        image: 'img/ride.jpg',
        audioSrc: 'audio/ride.mp3',
      },
      {
        word: 'run',
        translation: 'бегать',
        image: 'img/run.jpg',
        audioSrc: 'audio/run.mp3',
      },
      {
        word: 'sing',
        translation: 'петь',
        image: 'img/sing.jpg',
        audioSrc: 'audio/sing.mp3',
      },
      {
        word: 'skip',
        translation: 'прыгать',
        image: 'img/skip.jpg',
        audioSrc: 'audio/skip.mp3',
      },
      {
        word: 'swim',
        translation: 'плавать',
        image: 'img/swim.jpg',
        audioSrc: 'audio/swim.mp3',
      },
    ],

    [
      {
        word: 'cat',
        translation: 'кот',
        image: 'img/cat.jpg',
        audioSrc: 'audio/cat.mp3',
      },
      {
        word: 'chick',
        translation: 'цыплёнок',
        image: 'img/chick.jpg',
        audioSrc: 'audio/chick.mp3',
      },
      {
        word: 'chicken',
        translation: 'курица',
        image: 'img/chicken.jpg',
        audioSrc: 'audio/chicken.mp3',
      },
      {
        word: 'dog',
        translation: 'собака',
        image: 'img/dog.jpg',
        audioSrc: 'audio/dog.mp3',
      },
      {
        word: 'horse',
        translation: 'лошадь',
        image: 'img/horse.jpg',
        audioSrc: 'audio/horse.mp3',
      },
      {
        word: 'pig',
        translation: 'свинья',
        image: 'img/pig.jpg',
        audioSrc: 'audio/pig.mp3',
      },
      {
        word: 'rabbit',
        translation: 'кролик',
        image: 'img/rabbit.jpg',
        audioSrc: 'audio/rabbit.mp3',
      },
      {
        word: 'sheep',
        translation: 'овца',
        image: 'img/sheep.jpg',
        audioSrc: 'audio/sheep.mp3',
      },
    ],

    [
      {
        word: 'bird',
        translation: 'птица',
        image: 'img/bird.jpg',
        audioSrc: 'audio/bird.mp3',
      },
      {
        word: 'fish',
        translation: 'рыба',
        image: 'img/fish1.jpg',
        audioSrc: 'audio/fish.mp3',
      },
      {
        word: 'frog',
        translation: 'жаба',
        image: 'img/frog.jpg',
        audioSrc: 'audio/frog.mp3',
      },
      {
        word: 'giraffe',
        translation: 'жирафа',
        image: 'img/giraffe.jpg',
        audioSrc: 'audio/giraffe.mp3',
      },
      {
        word: 'lion',
        translation: 'лев',
        image: 'img/lion.jpg',
        audioSrc: 'audio/lion.mp3',
      },
      {
        word: 'mouse',
        translation: 'мышь',
        image: 'img/mouse.jpg',
        audioSrc: 'audio/mouse.mp3',
      },
      {
        word: 'turtle',
        translation: 'черепаха',
        image: 'img/turtle.jpg',
        audioSrc: 'audio/turtle.mp3',
      },
      {
        word: 'dolphin',
        translation: 'дельфин',
        image: 'img/dolphin.jpg',
        audioSrc: 'audio/dolphin.mp3',
      },
    ],

    [
      {
        word: 'skirt',
        translation: 'юбка',
        image: 'img/skirt.jpg',
        audioSrc: 'audio/skirt.mp3',
      },
      {
        word: 'pants',
        translation: 'брюки',
        image: 'img/pants.jpg',
        audioSrc: 'audio/pants.mp3',
      },
      {
        word: 'blouse',
        translation: 'блузка',
        image: 'img/blouse.jpg',
        audioSrc: 'audio/blouse.mp3',
      },
      {
        word: 'dress',
        translation: 'платье',
        image: 'img/dress.jpg',
        audioSrc: 'audio/dress.mp3',
      },
      {
        word: 'boot',
        translation: 'ботинок',
        image: 'img/boot.jpg',
        audioSrc: 'audio/boot.mp3',
      },
      {
        word: 'shirt',
        translation: 'рубашка',
        image: 'img/shirt.jpg',
        audioSrc: 'audio/shirt.mp3',
      },
      {
        word: 'coat',
        translation: 'пальто',
        image: 'img/coat.jpg',
        audioSrc: 'audio/coat.mp3',
      },
      {
        word: 'shoe',
        translation: 'туфли',
        image: 'img/shoe.jpg',
        audioSrc: 'audio/shoe.mp3',
      },
    ],

    [
      {
        word: 'sad',
        translation: 'грустный',
        image: 'img/sad.jpg',
        audioSrc: 'audio/sad.mp3',
      },
      {
        word: 'angry',
        translation: 'сердитый',
        image: 'img/angry.jpg',
        audioSrc: 'audio/angry.mp3',
      },
      {
        word: 'happy',
        translation: 'счастливый',
        image: 'img/happy.jpg',
        audioSrc: 'audio/happy.mp3',
      },
      {
        word: 'tired',
        translation: 'уставший',
        image: 'img/tired.jpg',
        audioSrc: 'audio/tired.mp3',
      },
      {
        word: 'surprised',
        translation: 'удивлённый',
        image: 'img/surprised.jpg',
        audioSrc: 'audio/surprised.mp3',
      },
      {
        word: 'scared',
        translation: 'испуганный',
        image: 'img/scared.jpg',
        audioSrc: 'audio/scared.mp3',
      },
      {
        word: 'smile',
        translation: 'улыбка',
        image: 'img/smile.jpg',
        audioSrc: 'audio/smile.mp3',
      },
      {
        word: 'laugh',
        translation: 'смех',
        image: 'img/laugh.jpg',
        audioSrc: 'audio/laugh.mp3',
      },
    ],

    // [{
    //   word: 'pray',
    //   translation: 'молиться',
    //   image: 'img/laugh.jpg',
    //   audioSrc: 'audio2/pray-us.mp3',
    //   audioQuote: 'MR/ringtones/pray.mp3',
    // }],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
  ],
  [
    [
      {
        word: 'cry2',
        translation: 'плакать',
        image: 'img/cry.jpg',
        audioSrc: 'audio/cry.mp3',
      },
      {
        word: 'dance2',
        translation: 'танцевать',
        image: 'img/dance.jpg',
        audioSrc: 'audio/dance.mp3',
      },
      {
        word: 'dive',
        translation: 'нырять',
        image: 'img/dive.jpg',
        audioSrc: 'audio/dive.mp3',
      },
      {
        word: 'draw',
        translation: 'рисовать',
        image: 'img/draw.jpg',
        audioSrc: 'audio/draw.mp3',
      },
      {
        word: 'fish',
        translation: 'ловить рыбу',
        image: 'img/fish.jpg',
        audioSrc: 'audio/fish.mp3',
      },
      {
        word: 'fly',
        translation: 'летать',
        image: 'img/fly.jpg',
        audioSrc: 'audio/fly.mp3',
      },
      {
        word: 'hug',
        translation: 'обнимать',
        image: 'img/hug.jpg',
        audioSrc: 'audio/hug.mp3',
      },
      {
        word: 'jump',
        translation: 'прыгать',
        image: 'img/jump.jpg',
        audioSrc: 'audio/jump.mp3',
      },
    ],

    [
      {
        word: 'open',
        translation: 'открывать',
        image: 'img/open.jpg',
        audioSrc: 'audio/open.mp3',
      },
      {
        word: 'play',
        translation: 'играть',
        image: 'img/play.jpg',
        audioSrc: 'audio/play.mp3',
      },
      {
        word: 'point',
        translation: 'указывать',
        image: 'img/point.jpg',
        audioSrc: 'audio/point.mp3',
      },
      {
        word: 'ride',
        translation: 'ездить',
        image: 'img/ride.jpg',
        audioSrc: 'audio/ride.mp3',
      },
      {
        word: 'run',
        translation: 'бегать',
        image: 'img/run.jpg',
        audioSrc: 'audio/run.mp3',
      },
      {
        word: 'sing',
        translation: 'петь',
        image: 'img/sing.jpg',
        audioSrc: 'audio/sing.mp3',
      },
      {
        word: 'skip',
        translation: 'прыгать',
        image: 'img/skip.jpg',
        audioSrc: 'audio/skip.mp3',
      },
      {
        word: 'swim',
        translation: 'плавать',
        image: 'img/swim.jpg',
        audioSrc: 'audio/swim.mp3',
      },
    ],

    [
      {
        word: 'cat',
        translation: 'кот',
        image: 'img/cat.jpg',
        audioSrc: 'audio/cat.mp3',
      },
      {
        word: 'chick',
        translation: 'цыплёнок',
        image: 'img/chick.jpg',
        audioSrc: 'audio/chick.mp3',
      },
      {
        word: 'chicken',
        translation: 'курица',
        image: 'img/chicken.jpg',
        audioSrc: 'audio/chicken.mp3',
      },
      {
        word: 'dog',
        translation: 'собака',
        image: 'img/dog.jpg',
        audioSrc: 'audio/dog.mp3',
      },
      {
        word: 'horse',
        translation: 'лошадь',
        image: 'img/horse.jpg',
        audioSrc: 'audio/horse.mp3',
      },
      {
        word: 'pig',
        translation: 'свинья',
        image: 'img/pig.jpg',
        audioSrc: 'audio/pig.mp3',
      },
      {
        word: 'rabbit',
        translation: 'кролик',
        image: 'img/rabbit.jpg',
        audioSrc: 'audio/rabbit.mp3',
      },
      {
        word: 'sheep',
        translation: 'овца',
        image: 'img/sheep.jpg',
        audioSrc: 'audio/sheep.mp3',
      },
    ],

    [
      {
        word: 'bird',
        translation: 'птица',
        image: 'img/bird.jpg',
        audioSrc: 'audio/bird.mp3',
      },
      {
        word: 'fish',
        translation: 'рыба',
        image: 'img/fish1.jpg',
        audioSrc: 'audio/fish.mp3',
      },
      {
        word: 'frog',
        translation: 'жаба',
        image: 'img/frog.jpg',
        audioSrc: 'audio/frog.mp3',
      },
      {
        word: 'giraffe',
        translation: 'жирафа',
        image: 'img/giraffe.jpg',
        audioSrc: 'audio/giraffe.mp3',
      },
      {
        word: 'lion',
        translation: 'лев',
        image: 'img/lion.jpg',
        audioSrc: 'audio/lion.mp3',
      },
      {
        word: 'mouse',
        translation: 'мышь',
        image: 'img/mouse.jpg',
        audioSrc: 'audio/mouse.mp3',
      },
      {
        word: 'turtle',
        translation: 'черепаха',
        image: 'img/turtle.jpg',
        audioSrc: 'audio/turtle.mp3',
      },
      {
        word: 'dolphin',
        translation: 'дельфин',
        image: 'img/dolphin.jpg',
        audioSrc: 'audio/dolphin.mp3',
      },
    ],

    [
      {
        word: 'skirt',
        translation: 'юбка',
        image: 'img/skirt.jpg',
        audioSrc: 'audio/skirt.mp3',
      },
      {
        word: 'pants',
        translation: 'брюки',
        image: 'img/pants.jpg',
        audioSrc: 'audio/pants.mp3',
      },
      {
        word: 'blouse',
        translation: 'блузка',
        image: 'img/blouse.jpg',
        audioSrc: 'audio/blouse.mp3',
      },
      {
        word: 'dress',
        translation: 'платье',
        image: 'img/dress.jpg',
        audioSrc: 'audio/dress.mp3',
      },
      {
        word: 'boot',
        translation: 'ботинок',
        image: 'img/boot.jpg',
        audioSrc: 'audio/boot.mp3',
      },
      {
        word: 'shirt',
        translation: 'рубашка',
        image: 'img/shirt.jpg',
        audioSrc: 'audio/shirt.mp3',
      },
      {
        word: 'coat',
        translation: 'пальто',
        image: 'img/coat.jpg',
        audioSrc: 'audio/coat.mp3',
      },
      {
        word: 'shoe',
        translation: 'туфли',
        image: 'img/shoe.jpg',
        audioSrc: 'audio/shoe.mp3',
      },
    ],

    [
      {
        word: 'sad',
        translation: 'грустный',
        image: 'img/sad.jpg',
        audioSrc: 'audio/sad.mp3',
      },
      {
        word: 'angry',
        translation: 'сердитый',
        image: 'img/angry.jpg',
        audioSrc: 'audio/angry.mp3',
      },
      {
        word: 'happy',
        translation: 'счастливый',
        image: 'img/happy.jpg',
        audioSrc: 'audio/happy.mp3',
      },
      {
        word: 'tired',
        translation: 'уставший',
        image: 'img/tired.jpg',
        audioSrc: 'audio/tired.mp3',
      },
      {
        word: 'surprised',
        translation: 'удивлённый',
        image: 'img/surprised.jpg',
        audioSrc: 'audio/surprised.mp3',
      },
      {
        word: 'scared',
        translation: 'испуганный',
        image: 'img/scared.jpg',
        audioSrc: 'audio/scared.mp3',
      },
      {
        word: 'smile',
        translation: 'улыбка',
        image: 'img/smile.jpg',
        audioSrc: 'audio/smile.mp3',
      },
      {
        word: 'laugh',
        translation: 'смех',
        image: 'img/laugh.jpg',
        audioSrc: 'audio/laugh.mp3',
      },
    ],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
  ],
  [
    [
      {
        word: 'cry',
        translation: 'плакать',
        image: 'img/cry.jpg',
        audioSrc: 'audio/cry.mp3',
      },
      {
        word: 'dance',
        translation: 'танцевать',
        image: 'img/dance.jpg',
        audioSrc: 'audio/dance.mp3',
      },
      {
        word: 'dive',
        translation: 'нырять',
        image: 'img/dive.jpg',
        audioSrc: 'audio/dive.mp3',
      },
      {
        word: 'draw',
        translation: 'рисовать',
        image: 'img/draw.jpg',
        audioSrc: 'audio/draw.mp3',
      },
      {
        word: 'fish',
        translation: 'ловить рыбу',
        image: 'img/fish.jpg',
        audioSrc: 'audio/fish.mp3',
      },
      {
        word: 'fly',
        translation: 'летать',
        image: 'img/fly.jpg',
        audioSrc: 'audio/fly.mp3',
      },
      {
        word: 'hug',
        translation: 'обнимать',
        image: 'img/hug.jpg',
        audioSrc: 'audio/hug.mp3',
      },
      {
        word: 'jump',
        translation: 'прыгать',
        image: 'img/jump.jpg',
        audioSrc: 'audio/jump.mp3',
      },
    ],

    [
      {
        word: 'open',
        translation: 'открывать',
        image: 'img/open.jpg',
        audioSrc: 'audio/open.mp3',
      },
      {
        word: 'play',
        translation: 'играть',
        image: 'img/play.jpg',
        audioSrc: 'audio/play.mp3',
      },
      {
        word: 'point',
        translation: 'указывать',
        image: 'img/point.jpg',
        audioSrc: 'audio/point.mp3',
      },
      {
        word: 'ride',
        translation: 'ездить',
        image: 'img/ride.jpg',
        audioSrc: 'audio/ride.mp3',
      },
      {
        word: 'run',
        translation: 'бегать',
        image: 'img/run.jpg',
        audioSrc: 'audio/run.mp3',
      },
      {
        word: 'sing',
        translation: 'петь',
        image: 'img/sing.jpg',
        audioSrc: 'audio/sing.mp3',
      },
      {
        word: 'skip',
        translation: 'прыгать',
        image: 'img/skip.jpg',
        audioSrc: 'audio/skip.mp3',
      },
      {
        word: 'swim',
        translation: 'плавать',
        image: 'img/swim.jpg',
        audioSrc: 'audio/swim.mp3',
      },
    ],

    [
      {
        word: 'cat',
        translation: 'кот',
        image: 'img/cat.jpg',
        audioSrc: 'audio/cat.mp3',
      },
      {
        word: 'chick',
        translation: 'цыплёнок',
        image: 'img/chick.jpg',
        audioSrc: 'audio/chick.mp3',
      },
      {
        word: 'chicken',
        translation: 'курица',
        image: 'img/chicken.jpg',
        audioSrc: 'audio/chicken.mp3',
      },
      {
        word: 'dog',
        translation: 'собака',
        image: 'img/dog.jpg',
        audioSrc: 'audio/dog.mp3',
      },
      {
        word: 'horse',
        translation: 'лошадь',
        image: 'img/horse.jpg',
        audioSrc: 'audio/horse.mp3',
      },
      {
        word: 'pig',
        translation: 'свинья',
        image: 'img/pig.jpg',
        audioSrc: 'audio/pig.mp3',
      },
      {
        word: 'rabbit',
        translation: 'кролик',
        image: 'img/rabbit.jpg',
        audioSrc: 'audio/rabbit.mp3',
      },
      {
        word: 'sheep',
        translation: 'овца',
        image: 'img/sheep.jpg',
        audioSrc: 'audio/sheep.mp3',
      },
    ],

    [
      {
        word: 'bird',
        translation: 'птица',
        image: 'img/bird.jpg',
        audioSrc: 'audio/bird.mp3',
      },
      {
        word: 'fish',
        translation: 'рыба',
        image: 'img/fish1.jpg',
        audioSrc: 'audio/fish.mp3',
      },
      {
        word: 'frog',
        translation: 'жаба',
        image: 'img/frog.jpg',
        audioSrc: 'audio/frog.mp3',
      },
      {
        word: 'giraffe',
        translation: 'жирафа',
        image: 'img/giraffe.jpg',
        audioSrc: 'audio/giraffe.mp3',
      },
      {
        word: 'lion',
        translation: 'лев',
        image: 'img/lion.jpg',
        audioSrc: 'audio/lion.mp3',
      },
      {
        word: 'mouse',
        translation: 'мышь',
        image: 'img/mouse.jpg',
        audioSrc: 'audio/mouse.mp3',
      },
      {
        word: 'turtle',
        translation: 'черепаха',
        image: 'img/turtle.jpg',
        audioSrc: 'audio/turtle.mp3',
      },
      {
        word: 'dolphin',
        translation: 'дельфин',
        image: 'img/dolphin.jpg',
        audioSrc: 'audio/dolphin.mp3',
      },
    ],

    [
      {
        word: 'skirt',
        translation: 'юбка',
        image: 'img/skirt.jpg',
        audioSrc: 'audio/skirt.mp3',
      },
      {
        word: 'pants',
        translation: 'брюки',
        image: 'img/pants.jpg',
        audioSrc: 'audio/pants.mp3',
      },
      {
        word: 'blouse',
        translation: 'блузка',
        image: 'img/blouse.jpg',
        audioSrc: 'audio/blouse.mp3',
      },
      {
        word: 'dress',
        translation: 'платье',
        image: 'img/dress.jpg',
        audioSrc: 'audio/dress.mp3',
      },
      {
        word: 'boot',
        translation: 'ботинок',
        image: 'img/boot.jpg',
        audioSrc: 'audio/boot.mp3',
      },
      {
        word: 'shirt',
        translation: 'рубашка',
        image: 'img/shirt.jpg',
        audioSrc: 'audio/shirt.mp3',
      },
      {
        word: 'coat',
        translation: 'пальто',
        image: 'img/coat.jpg',
        audioSrc: 'audio/coat.mp3',
      },
      {
        word: 'shoe',
        translation: 'туфли',
        image: 'img/shoe.jpg',
        audioSrc: 'audio/shoe.mp3',
      },
    ],

    [
      {
        word: 'sad',
        translation: 'грустный',
        image: 'img/sad.jpg',
        audioSrc: 'audio/sad.mp3',
      },
      {
        word: 'angry',
        translation: 'сердитый',
        image: 'img/angry.jpg',
        audioSrc: 'audio/angry.mp3',
      },
      {
        word: 'happy',
        translation: 'счастливый',
        image: 'img/happy.jpg',
        audioSrc: 'audio/happy.mp3',
      },
      {
        word: 'tired',
        translation: 'уставший',
        image: 'img/tired.jpg',
        audioSrc: 'audio/tired.mp3',
      },
      {
        word: 'surprised',
        translation: 'удивлённый',
        image: 'img/surprised.jpg',
        audioSrc: 'audio/surprised.mp3',
      },
      {
        word: 'scared',
        translation: 'испуганный',
        image: 'img/scared.jpg',
        audioSrc: 'audio/scared.mp3',
      },
      {
        word: 'smile',
        translation: 'улыбка',
        image: 'img/smile.jpg',
        audioSrc: 'audio/smile.mp3',
      },
      {
        word: 'laugh',
        translation: 'смех',
        image: 'img/laugh.jpg',
        audioSrc: 'audio/laugh.mp3',
      },
    ],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
  ],
  [
    [
      {
        word: 'cry',
        translation: 'плакать',
        image: 'img/cry.jpg',
        audioSrc: 'audio/cry.mp3',
      },
      {
        word: 'dance',
        translation: 'танцевать',
        image: 'img/dance.jpg',
        audioSrc: 'audio/dance.mp3',
      },
      {
        word: 'dive',
        translation: 'нырять',
        image: 'img/dive.jpg',
        audioSrc: 'audio/dive.mp3',
      },
      {
        word: 'draw',
        translation: 'рисовать',
        image: 'img/draw.jpg',
        audioSrc: 'audio/draw.mp3',
      },
      {
        word: 'fish',
        translation: 'ловить рыбу',
        image: 'img/fish.jpg',
        audioSrc: 'audio/fish.mp3',
      },
      {
        word: 'fly',
        translation: 'летать',
        image: 'img/fly.jpg',
        audioSrc: 'audio/fly.mp3',
      },
      {
        word: 'hug',
        translation: 'обнимать',
        image: 'img/hug.jpg',
        audioSrc: 'audio/hug.mp3',
      },
      {
        word: 'jump',
        translation: 'прыгать',
        image: 'img/jump.jpg',
        audioSrc: 'audio/jump.mp3',
      },
    ],

    [
      {
        word: 'open',
        translation: 'открывать',
        image: 'img/open.jpg',
        audioSrc: 'audio/open.mp3',
      },
      {
        word: 'play',
        translation: 'играть',
        image: 'img/play.jpg',
        audioSrc: 'audio/play.mp3',
      },
      {
        word: 'point',
        translation: 'указывать',
        image: 'img/point.jpg',
        audioSrc: 'audio/point.mp3',
      },
      {
        word: 'ride',
        translation: 'ездить',
        image: 'img/ride.jpg',
        audioSrc: 'audio/ride.mp3',
      },
      {
        word: 'run',
        translation: 'бегать',
        image: 'img/run.jpg',
        audioSrc: 'audio/run.mp3',
      },
      {
        word: 'sing',
        translation: 'петь',
        image: 'img/sing.jpg',
        audioSrc: 'audio/sing.mp3',
      },
      {
        word: 'skip',
        translation: 'прыгать',
        image: 'img/skip.jpg',
        audioSrc: 'audio/skip.mp3',
      },
      {
        word: 'swim',
        translation: 'плавать',
        image: 'img/swim.jpg',
        audioSrc: 'audio/swim.mp3',
      },
    ],

    [
      {
        word: 'cat',
        translation: 'кот',
        image: 'img/cat.jpg',
        audioSrc: 'audio/cat.mp3',
      },
      {
        word: 'chick',
        translation: 'цыплёнок',
        image: 'img/chick.jpg',
        audioSrc: 'audio/chick.mp3',
      },
      {
        word: 'chicken',
        translation: 'курица',
        image: 'img/chicken.jpg',
        audioSrc: 'audio/chicken.mp3',
      },
      {
        word: 'dog',
        translation: 'собака',
        image: 'img/dog.jpg',
        audioSrc: 'audio/dog.mp3',
      },
      {
        word: 'horse',
        translation: 'лошадь',
        image: 'img/horse.jpg',
        audioSrc: 'audio/horse.mp3',
      },
      {
        word: 'pig',
        translation: 'свинья',
        image: 'img/pig.jpg',
        audioSrc: 'audio/pig.mp3',
      },
      {
        word: 'rabbit',
        translation: 'кролик',
        image: 'img/rabbit.jpg',
        audioSrc: 'audio/rabbit.mp3',
      },
      {
        word: 'sheep',
        translation: 'овца',
        image: 'img/sheep.jpg',
        audioSrc: 'audio/sheep.mp3',
      },
    ],

    [
      {
        word: 'bird',
        translation: 'птица',
        image: 'img/bird.jpg',
        audioSrc: 'audio/bird.mp3',
      },
      {
        word: 'fish',
        translation: 'рыба',
        image: 'img/fish1.jpg',
        audioSrc: 'audio/fish.mp3',
      },
      {
        word: 'frog',
        translation: 'жаба',
        image: 'img/frog.jpg',
        audioSrc: 'audio/frog.mp3',
      },
      {
        word: 'giraffe',
        translation: 'жирафа',
        image: 'img/giraffe.jpg',
        audioSrc: 'audio/giraffe.mp3',
      },
      {
        word: 'lion',
        translation: 'лев',
        image: 'img/lion.jpg',
        audioSrc: 'audio/lion.mp3',
      },
      {
        word: 'mouse',
        translation: 'мышь',
        image: 'img/mouse.jpg',
        audioSrc: 'audio/mouse.mp3',
      },
      {
        word: 'turtle',
        translation: 'черепаха',
        image: 'img/turtle.jpg',
        audioSrc: 'audio/turtle.mp3',
      },
      {
        word: 'dolphin',
        translation: 'дельфин',
        image: 'img/dolphin.jpg',
        audioSrc: 'audio/dolphin.mp3',
      },
    ],

    [
      {
        word: 'skirt',
        translation: 'юбка',
        image: 'img/skirt.jpg',
        audioSrc: 'audio/skirt.mp3',
      },
      {
        word: 'pants',
        translation: 'брюки',
        image: 'img/pants.jpg',
        audioSrc: 'audio/pants.mp3',
      },
      {
        word: 'blouse',
        translation: 'блузка',
        image: 'img/blouse.jpg',
        audioSrc: 'audio/blouse.mp3',
      },
      {
        word: 'dress',
        translation: 'платье',
        image: 'img/dress.jpg',
        audioSrc: 'audio/dress.mp3',
      },
      {
        word: 'boot',
        translation: 'ботинок',
        image: 'img/boot.jpg',
        audioSrc: 'audio/boot.mp3',
      },
      {
        word: 'shirt',
        translation: 'рубашка',
        image: 'img/shirt.jpg',
        audioSrc: 'audio/shirt.mp3',
      },
      {
        word: 'coat',
        translation: 'пальто',
        image: 'img/coat.jpg',
        audioSrc: 'audio/coat.mp3',
      },
      {
        word: 'shoe',
        translation: 'туфли',
        image: 'img/shoe.jpg',
        audioSrc: 'audio/shoe.mp3',
      },
    ],

    [
      {
        word: 'sad',
        translation: 'грустный',
        image: 'img/sad.jpg',
        audioSrc: 'audio/sad.mp3',
      },
      {
        word: 'angry',
        translation: 'сердитый',
        image: 'img/angry.jpg',
        audioSrc: 'audio/angry.mp3',
      },
      {
        word: 'happy',
        translation: 'счастливый',
        image: 'img/happy.jpg',
        audioSrc: 'audio/happy.mp3',
      },
      {
        word: 'tired',
        translation: 'уставший',
        image: 'img/tired.jpg',
        audioSrc: 'audio/tired.mp3',
      },
      {
        word: 'surprised',
        translation: 'удивлённый',
        image: 'img/surprised.jpg',
        audioSrc: 'audio/surprised.mp3',
      },
      {
        word: 'scared',
        translation: 'испуганный',
        image: 'img/scared.jpg',
        audioSrc: 'audio/scared.mp3',
      },
      {
        word: 'smile',
        translation: 'улыбка',
        image: 'img/smile.jpg',
        audioSrc: 'audio/smile.mp3',
      },
      {
        word: 'laugh',
        translation: 'смех',
        image: 'img/laugh.jpg',
        audioSrc: 'audio/laugh.mp3',
      },
    ],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
  ],
  [
    [
      {
        word: 'cry',
        translation: 'плакать',
        image: 'img/cry.jpg',
        audioSrc: 'audio/cry.mp3',
      },
      {
        word: 'dance',
        translation: 'танцевать',
        image: 'img/dance.jpg',
        audioSrc: 'audio/dance.mp3',
      },
      {
        word: 'dive',
        translation: 'нырять',
        image: 'img/dive.jpg',
        audioSrc: 'audio/dive.mp3',
      },
      {
        word: 'draw',
        translation: 'рисовать',
        image: 'img/draw.jpg',
        audioSrc: 'audio/draw.mp3',
      },
      {
        word: 'fish',
        translation: 'ловить рыбу',
        image: 'img/fish.jpg',
        audioSrc: 'audio/fish.mp3',
      },
      {
        word: 'fly',
        translation: 'летать',
        image: 'img/fly.jpg',
        audioSrc: 'audio/fly.mp3',
      },
      {
        word: 'hug',
        translation: 'обнимать',
        image: 'img/hug.jpg',
        audioSrc: 'audio/hug.mp3',
      },
      {
        word: 'jump',
        translation: 'прыгать',
        image: 'img/jump.jpg',
        audioSrc: 'audio/jump.mp3',
      },
    ],

    [
      {
        word: 'open',
        translation: 'открывать',
        image: 'img/open.jpg',
        audioSrc: 'audio/open.mp3',
      },
      {
        word: 'play',
        translation: 'играть',
        image: 'img/play.jpg',
        audioSrc: 'audio/play.mp3',
      },
      {
        word: 'point',
        translation: 'указывать',
        image: 'img/point.jpg',
        audioSrc: 'audio/point.mp3',
      },
      {
        word: 'ride',
        translation: 'ездить',
        image: 'img/ride.jpg',
        audioSrc: 'audio/ride.mp3',
      },
      {
        word: 'run',
        translation: 'бегать',
        image: 'img/run.jpg',
        audioSrc: 'audio/run.mp3',
      },
      {
        word: 'sing',
        translation: 'петь',
        image: 'img/sing.jpg',
        audioSrc: 'audio/sing.mp3',
      },
      {
        word: 'skip',
        translation: 'прыгать',
        image: 'img/skip.jpg',
        audioSrc: 'audio/skip.mp3',
      },
      {
        word: 'swim',
        translation: 'плавать',
        image: 'img/swim.jpg',
        audioSrc: 'audio/swim.mp3',
      },
    ],

    [
      {
        word: 'cat',
        translation: 'кот',
        image: 'img/cat.jpg',
        audioSrc: 'audio/cat.mp3',
      },
      {
        word: 'chick',
        translation: 'цыплёнок',
        image: 'img/chick.jpg',
        audioSrc: 'audio/chick.mp3',
      },
      {
        word: 'chicken',
        translation: 'курица',
        image: 'img/chicken.jpg',
        audioSrc: 'audio/chicken.mp3',
      },
      {
        word: 'dog',
        translation: 'собака',
        image: 'img/dog.jpg',
        audioSrc: 'audio/dog.mp3',
      },
      {
        word: 'horse',
        translation: 'лошадь',
        image: 'img/horse.jpg',
        audioSrc: 'audio/horse.mp3',
      },
      {
        word: 'pig',
        translation: 'свинья',
        image: 'img/pig.jpg',
        audioSrc: 'audio/pig.mp3',
      },
      {
        word: 'rabbit',
        translation: 'кролик',
        image: 'img/rabbit.jpg',
        audioSrc: 'audio/rabbit.mp3',
      },
      {
        word: 'sheep',
        translation: 'овца',
        image: 'img/sheep.jpg',
        audioSrc: 'audio/sheep.mp3',
      },
    ],

    [
      {
        word: 'bird',
        translation: 'птица',
        image: 'img/bird.jpg',
        audioSrc: 'audio/bird.mp3',
      },
      {
        word: 'fish',
        translation: 'рыба',
        image: 'img/fish1.jpg',
        audioSrc: 'audio/fish.mp3',
      },
      {
        word: 'frog',
        translation: 'жаба',
        image: 'img/frog.jpg',
        audioSrc: 'audio/frog.mp3',
      },
      {
        word: 'giraffe',
        translation: 'жирафа',
        image: 'img/giraffe.jpg',
        audioSrc: 'audio/giraffe.mp3',
      },
      {
        word: 'lion',
        translation: 'лев',
        image: 'img/lion.jpg',
        audioSrc: 'audio/lion.mp3',
      },
      {
        word: 'mouse',
        translation: 'мышь',
        image: 'img/mouse.jpg',
        audioSrc: 'audio/mouse.mp3',
      },
      {
        word: 'turtle',
        translation: 'черепаха',
        image: 'img/turtle.jpg',
        audioSrc: 'audio/turtle.mp3',
      },
      {
        word: 'dolphin',
        translation: 'дельфин',
        image: 'img/dolphin.jpg',
        audioSrc: 'audio/dolphin.mp3',
      },
    ],

    [
      {
        word: 'skirt',
        translation: 'юбка',
        image: 'img/skirt.jpg',
        audioSrc: 'audio/skirt.mp3',
      },
      {
        word: 'pants',
        translation: 'брюки',
        image: 'img/pants.jpg',
        audioSrc: 'audio/pants.mp3',
      },
      {
        word: 'blouse',
        translation: 'блузка',
        image: 'img/blouse.jpg',
        audioSrc: 'audio/blouse.mp3',
      },
      {
        word: 'dress',
        translation: 'платье',
        image: 'img/dress.jpg',
        audioSrc: 'audio/dress.mp3',
      },
      {
        word: 'boot',
        translation: 'ботинок',
        image: 'img/boot.jpg',
        audioSrc: 'audio/boot.mp3',
      },
      {
        word: 'shirt',
        translation: 'рубашка',
        image: 'img/shirt.jpg',
        audioSrc: 'audio/shirt.mp3',
      },
      {
        word: 'coat',
        translation: 'пальто',
        image: 'img/coat.jpg',
        audioSrc: 'audio/coat.mp3',
      },
      {
        word: 'shoe',
        translation: 'туфли',
        image: 'img/shoe.jpg',
        audioSrc: 'audio/shoe.mp3',
      },
    ],

    [
      {
        word: 'sad',
        translation: 'грустный',
        image: 'img/sad.jpg',
        audioSrc: 'audio/sad.mp3',
      },
      {
        word: 'angry',
        translation: 'сердитый',
        image: 'img/angry.jpg',
        audioSrc: 'audio/angry.mp3',
      },
      {
        word: 'happy',
        translation: 'счастливый',
        image: 'img/happy.jpg',
        audioSrc: 'audio/happy.mp3',
      },
      {
        word: 'tired',
        translation: 'уставший',
        image: 'img/tired.jpg',
        audioSrc: 'audio/tired.mp3',
      },
      {
        word: 'surprised',
        translation: 'удивлённый',
        image: 'img/surprised.jpg',
        audioSrc: 'audio/surprised.mp3',
      },
      {
        word: 'scared',
        translation: 'испуганный',
        image: 'img/scared.jpg',
        audioSrc: 'audio/scared.mp3',
      },
      {
        word: 'smile',
        translation: 'улыбка',
        image: 'img/smile.jpg',
        audioSrc: 'audio/smile.mp3',
      },
      {
        word: 'laugh',
        translation: 'смех',
        image: 'img/laugh.jpg',
        audioSrc: 'audio/laugh.mp3',
      },
    ],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],

    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
    // [],
  ],
];

export default cards;
